HAST-164: SDK static code analysis integration
Lombiq/Arithmetics pull request #3
Opened 2021-12-20 03:36 UTC by DAud-IcI

HAST-164
Root PR: https://github.com/Lombiq/Hastlayer-SDK/pull/65

2021-12-22 01:04 UTC, Piedone requested changes

2021-12-22 01:04 UTC, Piedone commented on BitMask/BitMask.cs
> +                if (buffer % 2 != 0) segments[segmentPosition] += (uint)(1 << position);
Ez meg a 259. sor ellentétes az eredeti logikával. Szándékosan?

2021-12-22 01:04 UTC, Piedone commented on Posit/Posit.cs
> +            Justification = "It's really not that bad.")]
http://www.bash.org/?192888

2021-12-22 01:04 UTC, Piedone commented on Posit/Posit.cs
> +                                      left.FractionWithHiddenBit().FindMostSignificantOnePosition();
```suggestion
                scaleFactor += resultFractionBits.FindMostSignificantOnePosition() -
                    left.FractionWithHiddenBit().FindMostSignificantOnePosition();
```

2021-12-22 01:04 UTC, Piedone commented on Posit/Quire.cs
> +    [SuppressMessage("Major Code Smell", "S4035:Classes implementing \"IEquatable<T>\" should be sealed", Justification = "False Positive")]
```suggestion
    [SuppressMessage(
        "Major Code Smell",
        "S4035:Classes implementing \"IEquatable<T>\" should be sealed",
        Justification = "False positive, it actually implements IEqualityComparer<T>.")]

```

2021-12-22 01:04 UTC, Piedone commented on Unum/Unum.cs
> +                // In case of a negative exponent the.
![image](https://user-images.githubusercontent.com/1976647/147017042-cece807c-c87c-4bea-bf2a-4aac8fe86c07.png)

2021-12-22 02:00 UTC, DAud-IcI commented on BitMask/BitMask.cs
> +                if (buffer % 2 != 0) segments[segmentPosition] += (uint)(1 << position);
Logikailag nincs eltérés, hiszen a `% 2` eredménye csak 0 vagy 1 lehet ezért az "egyenlő egyel" és a "nem nulla" ugyanaz. Viszont az eredetire ezt a warningot dobja:

> Warning S2197 : The result of this modulus operation may not be positive.

Ugye ez nettó hülyeség, mert a `buffer` az egy `byte` ami unsigned típus ezért a `byte % 2` mindig pozitív. Gondoltam ez elegánsabb mint telepakolni pragmával.

2021-12-22 02:07 UTC, DAud-IcI commented on Unum/Unum.cs
> +                // In case of a negative exponent the.
🤷‍♀️ ¯\_(ツ)_/¯ 🤷‍♀️
Nemtom, én csak cut-paste-eltem őket elolvasás nélkül. [Ezt egyedül Álmos tudná megmondani.](https://github.com/Lombiq/Arithmetics/commit/6e115333e1f8dabb863c8c78375081e74e88c722#diff-b26de494690eeda55d1e7a77d321664566eb135cfe28c97a619c129d9a95b3c2R682)

2021-12-22 02:47 UTC, DAud-IcI commented on Unum/Unum.cs
> +                // In case of a negative exponent the.
Letöröltem.

2021-12-22 11:41 UTC, Piedone commented on BitMask/BitMask.cs
> +                if (buffer % 2 != 0) segments[segmentPosition] += (uint)(1 << position);
Jaaa, OK.

2021-12-25 03:32 UTC, Piedone approved these changes

2021-12-29 01:25 UTC, merged